Inclusão do endpoints
fga-eps-mds/2022-2-CAPJu-User-New pull request #3
Opened 2023-01-25 02:42 UTC by AntonioAldisio

retirada do endpoints que se encontrava no services

2023-01-25 03:30 UTC, DaviAntonio commented on src/routes.js
> +// FIXME: endpoint igual ao alluser qual tevemos manter ? o vitor que criou esse endpoint posso excluir ?
`allUser` é usada em alguns lugares do front-end para ler os usuários aceitos ou não aceitos

2023-01-25 03:31 UTC, DaviAntonio approved these changes

2023-01-25 22:27 UTC, AntonioAldisio commented on src/routes.js
> +// FIXME: endpoint igual ao alluser qual tevemos manter ? o vitor que criou esse endpoint posso excluir ?
sim, tbm fique na duvida em relação a isso. Precisamos definir onde ira ficar esse endpoint

2023-01-27 16:34 UTC, DaviAntonio requested changes

2023-01-27 16:34 UTC, DaviAntonio commented on src/controllers/UserController.js
> +                    email: user.email,
Adicionar
`idRole: user.idRole,`
ou quebrará o verificador de permissões do front-end.
Adicionei essa modificação em fga-eps-mds/2022-2-CAPJu-Service@022d3bcc

2023-01-28 03:12 UTC, DaviAntonio approved these changes
ok

2023-01-28 03:13 UTC, ilus1 approved these changes

2023-01-28 03:14 UTC, merged